route_name: "default"
waypoints:
  - x: 3.12
    y: -9.65
    yaw_deg: 180
    action_id: 31
    say_text: "到达党建和创讲解点"
  - x: 0.21
    y: -0.12
    yaw_deg: 180
    action_id: 31
    say_text: "到达移动5G展区。中国移动 5G 智享套餐，多档位满足不同需求，128 元起含 30GB 全国流量 + 500 分钟通话，网速快、覆盖广。畅享高清视频、云游戏，享 5G 优享服务、移动云盘、视频会员等权益，全国通用、老用户免换卡升级，办理便捷，性价比高。"